### ISSUE TITLE
An alternate way to load the DLL

### ISSUE THREAD

**Issue by Awesomerly** [DeltaNeverUsed/WebfishingDECTalk#1]
People in the webfishing modding discord noticed that the mod isn't working for them.

Looking at your repository I notice that you are using a .gdnlib and .gdns file to load the DLL. This works in the editor as long as the path is correct but I had trouble trying to get that approach to work in the actual game, because there wasn't really a way to pack the DLL into the .pck or get it to load from inside there.

The approach that worked for me comes from NotNite's [WebfishingRichPresence](https://github.com/NotNite/WebfishingRichPresence/blob/13abe24509360eea518d1c207b8fed9d4e415ac2/project/mods/WebfishingRichPresence/main.gd#L6). What NotNite does is she manually creates a GDNativeLibrary object, sets the configuration data to load the dll from `%LIBRPCPATH%`, then makes a NativeScript object with that library and attaches it to a node/puts it on the scene tree. THEN, she has a C# patch to replace the string `%LIBRPCPATH%` with the actual path of the dll. I have no idea how she came up with this madness but it works :)

I hope this helps. Thank you for making this mod.

P.S. The version of DECTalk that sounds exactly the same as moonbase alpha is 4.6.4 demo (which doesnt have a DLL sadly, but maybe one of the 4.6.4 releases from this page are close enough: https://datajake.braillescreen.net/tts/dectalk%20software%20and%20manual/). Also, I don't know if you got this detail down but in order to make it sound like moonbase alpha you have to upsample it without interpolation to get all the high end sound in there.

**Comment by DeltaNeverUsed** [comment]
Mmm
Yeah, I see. I did notice that and tried to do something to fix it, but that does sound like a way better method.
I have no idea if the thing I tried to do works or not, had just been waiting for the stuff to update in the mod manager... :(

> Also, I don't know if you got this detail down but in order to make it sound like moonbase alpha you have to upsample it without interpolation to get all the high end sound in there.

Had no idea, I should probably do that, might as well.

**Comment by Awesomerly** [comment]
:)

**Comment by DeltaNeverUsed** [comment]
That'll be a tomorrow to-do for me :3

**Comment by Awesomerly** [comment]
:3

**Comment by MochaAmour** [comment]
Sorry a bit unrelated but i tried looking it up and found nothing whats this about a webfishing modding discord?

**Comment by Awesomerly** [comment]
https://thunderstore.io/c/webfishing/

It is listed on the thunderstore page.

Here's a direct link:

https://discord.gg/HzhCPxeCKY

**Comment by DeltaNeverUsed** [comment]
> you have to upsample it without interpolation to get all the high end sound in there.

Do you have a source for this?
And is it just like constant every sample in the 11.025khz is four in the 44.1khz buffer?

**Comment by Awesomerly** [comment]
The source was I talked to someone in 7coil's discord server. 7coil is the guy who made the dectalk repository. I saw that moonbase alpha used libresample so maybe use something like that?

**Comment by DeltaNeverUsed** [comment]
Mmmm... I see.

Also, that alternate method of doing the DLL loading seems to work pretty well, but there's one small issue, and that is that the DECTalk.dll still tries to load the stuff it needs from the game's folder...

**Comment by DeltaNeverUsed** [comment]
Okay, I uploaded a version that hopefully should work to Thunderstore, if you could test it out @Awesomerly, that'd be great!
I would do it myself, but I don't have a way I could easily test it with a mod manager.

**Comment by river58** [comment]
Works for me atleast! I wasn't able to hear the voices before but now I can after the update.

**Comment by DeltaNeverUsed** [comment]
> Works for me atleast! I wasn't able to hear the voices before but now I can after the update.

@Awesomerly helped me trouble shoot in discord DMs. thanks for confirming that it works for other people than us two!
I'll close this issue now.
